### ISSUE TITLE
Domain down?

### ISSUE THREAD

**Issue by Jean85** [greydnls/code-manifesto#80]
Hi there... I listened to your keynote at PHPDay about the Code manifesto, and while writing a blog entry about the conf I found out that the Code Manifesto site seems not working: right now I get a ERR_NAME_NOT_RESOLVED with Chrome... 

The DNS domain info seems ok but updated yesterday, maybe it was just renewed?

**Comment by greydnls** [comment]
Yeah, that's my bad. I let it expire. Just set it up for renewal, should be resolved shortly. Thanks!

**Comment by Jean85** [comment]
It's already working, thanks!

**Comment by Potherca** [comment]
It might be time to re-open this issue as it looks like codemanifesto.com is down again :-(

**Comment by greydnls** [comment]
Actually the domain just lapsed, unfortunately. I'm going to work on
getting a static site set up, hosted on GitHub pages or similar.

**Comment by Potherca** [comment]
If you want any assistance with that, don't hesitate to reach out 👍
