### ISSUE TITLE
Problem with Italian translation

### ISSUE THREAD

**Issue by garak** [greydnls/code-manifesto#84]
The first two sentences (point 1 and 2) are translated in Italian with an inconsistency.

1: "Discrimination limits us" --> "La discriminazione ci limita" (so far so good)
2: "Boundaries honor us" --> "Sapersi limitare è un onore" here is the problem

The term "boundaries" is currently translated with "sapersi limitare", that is literally "being able to limit ourselves". So there's the aforementioned inconsistency, because the verb "to limit" is used in a negative form in the first point, while the same verb (in the Italian translation) is used in a positive form.

I'm currently unable to propose a better translation for "boundaries", unless someone provides some relevant synonym

**Comment by giorrrgio** [comment]
@garak "E' un onore riconoscere i confini"/"Onoriamo i confini"/"Rispettiamo i confini"/"Andiamo fieri dei confini" WDYT?

**Comment by garak** [comment]
"Rispettiamo i confini" looks good to me. But then, we need to also change, in point 2, "stai oltrepassando i limiti" with something that void the word "limite/limiti". Maybe "stai andando oltre"?

**Comment by giorrrgio** [comment]
"stai oltrepassando i limiti" ->  "stai andando oltre", "stai trascendendo", "stai esagerando", "stai travalicando", "stai passando il segno"
